sprky/sprky_chess

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb
config/locales/devise.en.yml

This is the addition of the gems for devise, bourbon, and neat.  A model has not been created that uses devise.

added devise, borboun, and neat

---

db/schema.rb

This solves the error that was generated on the failed build for @hsinkoff 's commit #1 68dc8a8

run initial migration to setup schema

---

app/models/game.rb
app/models/piece.rb
app/models/player.rb
db/migrate/20150227214752_create_games.rb
db/migrate/20150227215405_create_pieces.rb
db/migrate/20150227220024_create_players.rb
db/schema.rb
test/fixtures/games.yml
test/fixtures/pieces.yml
test/fixtures/players.yml
test/models/game_test.rb
test/models/piece_test.rb
test/models/player_test.rb

based upon [http://dbpatterns.com/documents/54e79c721514b43cb25d8de7/]()

add Game, Piece, Player model and attributes based on initial data model

---

app/models/player.rb
config/environments/test.rb
config/routes.rb
db/migrate/20150301222649_add_devise_to_players.rb
db/schema.rb
test/fixtures/players.yml

This is the last step for using the devise gem.  It is now setup for the Player model and can be used.

Devise for player

---

Gemfile
Gemfile.lock
app/controllers/games_controller.rb
app/views/games/new.html.erb
app/views/games/show.html.erb
test/controllers/games_controller_test.rb
test/factories.rb
test/test_helper.rb

Added functionality to allow game joining
- Game creation adds current user as white_player_id
- In games#show if black_player_id.nil? allows current player to joing as black_player_id
!! note that currently both player ids can be == !!
- At some point it makes sense for the players to be assigned color randomly.
- Added factory girl and 2 factories (player and game)

Game joining

---

test/controllers/games_controller_test.rb
test/factories.rb

- remove hardcoded game.white_player_id in factories.rb
- change game to local variable instead of instance variable
- add 'create game test' to game_controller_test.rb to reflect how application assigns the user who creates the game to game.white_player_id

refactor game tests to reflect application logic

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/base/_base.scss
app/assets/stylesheets/base/_buttons.scss
app/assets/stylesheets/base/_forms.scss
app/assets/stylesheets/base/_grid-settings.scss
app/assets/stylesheets/base/_lists.scss
app/assets/stylesheets/base/_tables.scss
app/assets/stylesheets/base/_typography.scss
app/assets/stylesheets/base/_variables.scss

Bitters is Thoughtbot's base project styling for bourbon / neat. It sets up things like variables, grid settings, buttons, forms, lists, tables and  typography.
I added Bitters so we don't have do custom base styling we can just run with this and change as needed.

add bourbon-bitters for base styling

---

db/schema.rb

This updates the Piece model so that we no longer have name as a string.

changes Piece to no longer include name

---

app/models/game.rb
test/controllers/games_controller_test.rb
test/models/game_test.rb

This will address the issue Ken and Aaron were discussing for initializing the board.  It switches the initializing to after_create as Ken suggested and then I also added a test.

Piece location

---

app/models/bishop.rb
app/models/king.rb
app/models/knight.rb
app/models/pawn.rb
app/models/piece.rb
app/models/queen.rb
app/models/rook.rb
db/migrate/20150309185113_remove_name_from_piece.rb

This adds new files in the models folder so that each Piece type(Pawn, Rook, etc.) have their own file as Ken suggested last Friday.

added files in the models folder for each piece type

---

Gemfile
Gemfile.lock

Never got any feedback on adding byebug.  I find it useful for testing.  Just add ```byebug``` anywhere in your ruby code and execution will pause.  You can go into your server terminal window and access any variables at that state.  There are also lots of other actions you can perform.  https://github.com/deivid-rodriguez/byebug

Add byebug gem

---

app/controllers/games_controller.rb
app/views/games/show.html.erb
test/controllers/games_controller_test.rb

Ensures that joining player is not player who created game
- only show join game button when appropriate
- created game assigns a white player.  Any time black_player_id is nil the game is available to join
Randomized join
- after joining a game, the white and black player and swapped 50% of the time.
Add tests
- ensure that game join fails for black and white player ids equal

Randomize game join and ensure unique

---

app/models/bishop.rb
app/models/game.rb
app/models/king.rb
app/models/knight.rb
app/models/pawn.rb
app/models/piece.rb
app/models/queen.rb
app/models/rook.rb
test/factories.rb
test/models/pawn_test.rb
test/models/piece_test.rb
test/models/rook_test.rb

1. Implement the foundational logic for determining whether a move is valid / legal. 
- a 'valid' move is called on the Piece. the move must be :
- on the board
- 'legal' (according to each individual piece type)
- A 'legal' move has unique conditions depending on each piece type.
- Implement example `legal_move?` method for the following piece types:
- Pawn
- Rook
- Write tests
2. Refactor Piece
- remove `initialize` method for each piece
- add `set_default_images` method to Piece model
- call `set_default_images` using `after_initialize` hook
- add `color_name` method to Piece model - determines color as a string depending on piece.color
- dynamically generate `piece.symbol`
- use a loop to create pawns for the `initialize_board!` method

Foundational valid_move? logic AND refactor Piece  

---

Gemfile

move byebug out of development and into general gems

Move byebug gem

---

app/models/game.rb

This updates the color to be boolean (true, false) instead of (0=false, 1=true).

updating boolean values

---

app/models/bishop.rb
app/models/game.rb
app/models/pawn.rb
test/factories.rb
test/models/bishop_test.rb
test/models/pawn_test.rb

Add bishop factory
Add tests for legal and illegal bishop moves
Add valid_move?(x, y) 
1. just ensure that x and y absolute movement are equal

Bishop logic

---

app/models/pawn.rb

I just removed the extra puts statements and comments. Made no changes to the logic.

Update pawn model 

---

app/models/game.rb
test/models/game_test.rb

Wrote tests to check new obstruction? method
Modified method to return either nil or the piece causing the obstruction

Obstruction method return piece

---

app/models/pawn.rb
test/models/pawn_test.rb

add capture_move? logic for pawn. refactor tests

Pawn capture

---

app/models/game.rb
app/models/rook.rb
test/models/game_test.rb

PR got accepted before I could add this tweak.

Remove ? from obstruction method

---

app/models/queen.rb
test/factories.rb
test/models/queen_test.rb

combines move logic of rook and bishop to make queen's legal_move? logic

add initial queen legal_move? logic

---

app/models/knight.rb
test/factories.rb
test/models/knight_test.rb

returns false if: diagonal move, horizontal, or vertical
returns true if: x is equal to 2 and y is equal to 1 (or visa versa)

add initial knight legal_move? logic

---

app/models/bishop.rb
app/models/rook.rb

Nothing major here. Just taking out unnecessary `self`, `do` and a few other things. Reduce code bishop and rook move logic by 18 lines. Just trying to keep our code lean.

minor refactor for bishop and rook

---

app/models/knight.rb

per @washburnad's comment on previous logic, updated proper_length?

update knight legal_move?

---

app/models/bishop.rb
app/models/piece.rb
app/models/queen.rb
app/models/rook.rb
test/factories.rb
test/models/bishop_test.rb
test/models/queen_test.rb
test/models/rook_test.rb

There is a lot of repetitive code in this section.  We will probably want to deal with that later, but I wanted the group to have a chance to see the code.

Bishop and Queen obstructed_move methods

---

app/assets/stylesheets/_games.css.scss
app/views/shared/_gameboard.html.erb
test/controllers/games_controller_test.rb

The game partial checks to see if @game exits and current player is black player then renders the board from the black player side.  If current player is white player or not a player in this game it renders the board from the white player side.
Any thoughts on how to test this?

Responsive game board

---

app/assets/stylesheets/_games.css.scss
app/assets/stylesheets/_global.css.scss
app/controllers/application_controller.rb
app/controllers/games_controller.rb
app/controllers/static_pages_controller.rb
app/helpers/games_helper.rb
app/views/games/show.html.erb
app/views/shared/_game_details.html.erb
app/views/shared/_my_games.html.erb
app/views/shared/_open_games.html.erb
app/views/static_pages/index.html.erb

Displays player emails instead of ids
Linkable list of current players games
I'd like to hold off on this PR. I moved code around and took game board out of a ul and removed an hgroup.  Waiting to hear back from @johnellison for guidance.

Display list of current_players games

---

app/assets/javascripts/pieces.js.coffee
app/assets/stylesheets/pieces.css.scss
app/controllers/pieces_controller.rb
app/helpers/pieces_helper.rb
app/models/piece.rb
app/models/rook.rb
app/views/games/show.html.erb
app/views/pieces/update.html.erb
app/views/shared/_gameboard.html.erb
config/routes.rb
test/controllers/pieces_controller_test.rb
test/helpers/pieces_helper_test.rb
test/models/bishop_test.rb
test/models/queen_test.rb

This is good to go if you guys approve.  I've made line notes in the changed files.

Connect move piece

---

app/controllers/pieces_controller.rb
app/models/pawn.rb
app/models/piece.rb
test/models/pawn_test.rb
test/models/piece_test.rb

- add capture_move? to Piece.rb
- implement capture logic inside move_to
- test capture_move? and move_to
- modify capture_move? for Pawn.rb

Connect capture

---

.rubocop.yml
Gemfile
db/schema.rb

Added excluded files to rubocop.yml per rubocop recommendatiosn
Move gem out of test because heroku was trying to access it.

Rubo remove schema

---

app/assets/stylesheets/_games.css.scss
app/controllers/games_controller.rb
app/controllers/pieces_controller.rb
app/helpers/games_helper.rb
app/models/game.rb
app/models/piece.rb
app/views/shared/_gameboard.html.erb
db/migrate/20150331165327_add_turn_to_games.rb
db/schema.rb
test/controllers/pieces_controller_test.rb
test/models/piece_helper_methods_test.rb

Basics of turn taking work.  Bug in assigning player_id that is preventing turn taking from actually happening in the game.

Taking turns

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/games_controller.rb
app/helpers/application_helper.rb
app/models/game.rb
app/views/layouts/application.html.erb
app/views/shared/_gameboard.html.erb
test/controllers/pieces_controller_test.rb
test/models/game_test.rb

Assigns player_id to each piece after succesful game join
Remove turbolinks so that pieces are clickable without page reload

Assign player id to pieces

---

app/models/pawn.rb
test/models/pawn_capture_obstructed_test.rb
test/models/pawn_legal_move_test.rb

This should fix [Issue 52](https://github.com/sprky/sprky_chess/issues/62).

fix pawn destination obstruction bug

---

app/models/piece.rb
app/views/dashboards/show.html.erb

Puts open_games into dashboard.
Allows joining of open games.
Turn switching is correctly placed so that turn doesn't swap on invalid move.

Turn taking

---

app/models/game.rb
app/models/king.rb
app/models/piece.rb
test/models/piece_valid_move_to_test.rb

Moved king-specific `move_to logic` into a `move_to` method inside `king.rb`. Cleaned up a few other method calls.

Decouple king move to

---

app/controllers/dashboards_controller.rb

My bad on this one.  Moved my_games and open_games methods out of the applications_controller into static_page_controller but should have gone to dashboard controller.

Move methods to dashboard controller

---

app/models/pawn.rb
test/models/pawn_promotion_test.rb

Added some tests for pawn promotion and added a valid_move check to make them pass

Added pawn promotion tests and fixed errors

---

app/models/king.rb
test/models/king_test.rb
test/models/piece_transactions_test.rb

Add king tests
Add new file - piece_transactions_test.rb to ensure that transaction are completed or rollback completely on failure

Piece transaction testing

---

app/models/bishop.rb
app/models/concerns/obstructions.rb
app/models/game.rb
app/models/king.rb
app/models/knight.rb
app/models/pawn.rb
app/models/piece.rb
app/models/queen.rb
app/models/rook.rb
test/models/game_checking_test.rb

So, I took @hsinkoff 's blocking method and refactored out all of the logic it shared with obstructions. The result makes for very clean obstruction and checkmate logic.
Could definitely use another set of eyes for possible clean up, refactoring and more testing.  All existing tests pass but I didn't add tests for the modified methods.

Refactor obstructions

---

app/models/piece.rb
test/models/game_checking_test.rb

@hsinkoff, great job on this branch.  I did go ahead and just debug this and found that nesting your iterators differently worked perfectly.
I think we need more tests before merging but this works.
It also needs to be refactored to please RuboCop.  I'll work on that.

Blocking check

---

app/models/piece.rb
test/models/piece_transactions_test.rb

Turn was switching on failed attempt_move.  Added a rollback on move_to to prevent switch_turns from being called.

Fix turn taking

---

app/views/static_pages/index.html.erb

Getting the ball rolling on code-snippets.  Feel free to use different snippets or word-smith the text.  I also added target="_blank" to our individual links so that they open in a new page.
@hsinkoff @MCHLWRRN would you prefer to link to your LinkedIn page rather than to an email contact?

Add code snippets

---

app/views/static_pages/index.html.erb

Thanks @kenmazaika for noticing this.

Fix merge conflict

---

app/models/game.rb
app/models/pawn.rb
app/models/piece.rb
test/models/pawn_en_passant_test.rb
test/models/pawn_legal_move_test.rb

En passant is working and tested.

En passant

---

app/assets/javascripts/gameboard.js
app/views/static_pages/index.html.erb

I just added the js code I refactored into the code sample on the home page and updated the description a bit.

update js code sample and description.
